name: AI Daily Report

on:
  schedule:
    - cron: "0 5 * * *"   # 07:00 CEST körül
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser beautifulsoup4 python-dotenv openai

      - name: Run generator
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          python your_script.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _ai-daily-en/*.md _ai-daily-hu/*.md output/**/*.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "AI Daily auto-publish: $(date -u +'%Y-%m-%d')"
            git push origin master
          fi
