name: Publish AI Daily from output

on:
  push:
    branches: [ master ]
    paths:
      - "output/**.md"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Copy todays files into collections and add categories if missing
        run: |
          TODAY=$(date +%F)
          EN="output/${TODAY}/${TODAY}-ai-daily-report.md"
          HU="output/${TODAY}/${TODAY}-ai-daily-report-hu.md"

          mkdir -p _ai-daily-en _ai-daily-hu

          add_category() {
            FILE="$1"
            CAT="$2"
            if [ ! -f "$FILE" ]; then
              echo "Missing $FILE"; return
            fi
            # ha nincs front matter, tegyünk
            if ! head -n1 "$FILE" | grep -q '^---$'; then
              echo -e "---\ncategories: [${CAT}]\n---\n$(cat "$FILE")" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
            else
              # ha van, de nincs categories sor, szúrjuk be a 2. sor után
              if ! awk '/^---$/{inFM=!inFM} inFM && /^categories: \[.*\]$/{found=1} END{exit !found}' "$FILE"; then
                awk 'BEGIN{inFM=0; inserted=0}
                  /^---$/ {print; inFM=!inFM; next}
                  { if(inFM && !inserted){print; print "categories: ['"${CAT}"']"; inserted=1} else print }' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
              fi
            fi
          }

          cp "$EN" "_ai-daily-en/$(basename "$EN")"
          cp "$HU" "_ai-daily-hu/$(basename "$HU")"

          add_category "_ai-daily-en/$(basename "$EN")" "ai-daily-en"
          add_category "_ai-daily-hu/$(basename "$HU")" "ai-daily-hu"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _ai-daily-en/*.md _ai-daily-hu/*.md
          if git diff --cached --quiet; then
            echo "Nothing to publish."
          else
            git commit -m "Publish AI Daily (from output)"
            git push origin master
          fi
